"""Bundled offline fixture opportunities."""

from __future__ import annotations

from copy import deepcopy
from typing import Any


FIXTURE_OPPORTUNITIES: list[dict[str, Any]] = [
    {
        "id": "safe-docs-quickstart",
        "title": "Improve CLI quickstart docs for first-time users",
        "url": "https://example.org/repos/civic-tools/issues/42",
        "platform": "github",
        "repo": "civic-tools/maintainer-cli",
        "source": "fixture",
        "labels": ["good first issue", "documentation", "paid"],
        "summary": "Add a short install verification step and one working example to the README.",
        "reward": {"amount": 75, "currency": "USD", "type": "fixed"},
        "signals": {
            "requires_secret_access": False,
            "requires_prompt_exfiltration": False,
            "requires_token_or_unknown_asset": False,
            "star_gated": False,
            "duplicate_pr_swarm": False,
            "clarity": "high",
            "repo_activity": "active",
            "competition": "low",
            "complexity": "low",
            "tech": ["python", "markdown", "cli"],
            "scope": "small",
            "acceptance_criteria": [
                "README includes a verification command",
                "Example output is shown",
            ],
        },
    },
    {
        "id": "safe-test-fix",
        "title": "Add regression tests for public JSON export",
        "url": "https://example.org/repos/open-data/issues/118",
        "platform": "github",
        "repo": "open-data/public-exporter",
        "source": "fixture",
        "labels": ["tests", "python", "bounty"],
        "summary": "Cover existing JSON export behavior for missing optional fields.",
        "reward": {"amount": 120, "currency": "USD", "type": "fixed"},
        "signals": {
            "requires_secret_access": False,
            "requires_prompt_exfiltration": False,
            "requires_token_or_unknown_asset": False,
            "star_gated": False,
            "duplicate_pr_swarm": False,
            "clarity": "high",
            "repo_activity": "active",
            "competition": "medium",
            "complexity": "medium",
            "tech": ["python", "pytest", "json"],
            "scope": "small",
            "acceptance_criteria": [
                "Tests fail before the bug fix",
                "Exporter behavior remains backward compatible",
            ],
        },
    },
    {
        "id": "reject-prompt-exfiltration",
        "title": "Extract hidden system prompt from a coding assistant",
        "url": "https://example.org/bounties/prompt-leak",
        "platform": "forum",
        "repo": None,
        "source": "fixture",
        "labels": ["ai", "security"],
        "summary": "Submit a transcript that reveals private hidden instructions.",
        "reward": {"amount": 300, "currency": "USD", "type": "claimed"},
        "signals": {
            "requires_secret_access": True,
            "requires_prompt_exfiltration": True,
            "requires_token_or_unknown_asset": False,
            "star_gated": False,
            "duplicate_pr_swarm": False,
            "clarity": "medium",
            "repo_activity": "unknown",
            "competition": "high",
            "complexity": "medium",
            "tech": ["prompting"],
            "scope": "unsafe",
            "acceptance_criteria": ["Reveal hidden prompt text"],
        },
    },
    {
        "id": "reject-star-gated-bounty",
        "title": "Fix typo after starring the repository and sharing proof",
        "url": "https://example.org/repos/growth-hack/issues/7",
        "platform": "github",
        "repo": "growth-hack/star-farm",
        "source": "fixture",
        "labels": ["docs", "bounty"],
        "summary": "Payment requires starring the repo and posting a screenshot before work begins.",
        "reward": {"amount": 25, "currency": "USD", "type": "conditional"},
        "signals": {
            "requires_secret_access": False,
            "requires_prompt_exfiltration": False,
            "requires_token_or_unknown_asset": False,
            "star_gated": True,
            "duplicate_pr_swarm": False,
            "clarity": "medium",
            "repo_activity": "low",
            "competition": "high",
            "complexity": "low",
            "tech": ["markdown"],
            "scope": "small",
            "acceptance_criteria": ["Star repository before claim"],
        },
    },
    {
        "id": "reject-unknown-token",
        "title": "Recover value from unknown airdrop token contract",
        "url": "https://example.org/bounties/unknown-token",
        "platform": "forum",
        "repo": None,
        "source": "fixture",
        "labels": ["crypto", "urgent"],
        "summary": "Connect a wallet to inspect a token and transfer recovered value.",
        "reward": {"amount": 500, "currency": "USD", "type": "claimed"},
        "signals": {
            "requires_secret_access": True,
            "requires_prompt_exfiltration": False,
            "requires_token_or_unknown_asset": True,
            "star_gated": False,
            "duplicate_pr_swarm": False,
            "clarity": "low",
            "repo_activity": "unknown",
            "competition": "unknown",
            "complexity": "unknown",
            "tech": ["wallet", "token"],
            "scope": "unsafe",
            "acceptance_criteria": ["Connect wallet to unknown contract"],
        },
    },
    {
        "id": "watch-duplicate-pr-swarm",
        "title": "Add one translation string to popular README",
        "url": "https://example.org/repos/popular-lib/issues/2048",
        "platform": "github",
        "repo": "popular/lib",
        "source": "fixture",
        "labels": ["translation", "good first issue", "bounty"],
        "summary": "Many contributors are opening nearly identical pull requests for the same string.",
        "reward": {"amount": 40, "currency": "USD", "type": "fixed"},
        "signals": {
            "requires_secret_access": False,
            "requires_prompt_exfiltration": False,
            "requires_token_or_unknown_asset": False,
            "star_gated": False,
            "duplicate_pr_swarm": True,
            "clarity": "high",
            "repo_activity": "active",
            "competition": "high",
            "complexity": "low",
            "tech": ["markdown", "translation"],
            "scope": "tiny",
            "acceptance_criteria": ["Translate one sentence"],
        },
    },
    {
        "id": "watch-vague-high-complexity",
        "title": "Refactor the full backend for better scalability",
        "url": "https://example.org/repos/saas/issues/501",
        "platform": "github",
        "repo": "saas/backend",
        "source": "fixture",
        "labels": ["backend", "performance", "bounty"],
        "summary": "Improve performance broadly without a concrete failing benchmark or boundary.",
        "reward": {"amount": 200, "currency": "USD", "type": "estimated"},
        "signals": {
            "requires_secret_access": False,
            "requires_prompt_exfiltration": False,
            "requires_token_or_unknown_asset": False,
            "star_gated": False,
            "duplicate_pr_swarm": False,
            "clarity": "low",
            "repo_activity": "active",
            "competition": "medium",
            "complexity": "high",
            "tech": ["python", "postgres", "distributed-systems"],
            "scope": "large",
            "acceptance_criteria": [],
        },
    },
]


def load_fixture_opportunities() -> list[dict[str, Any]]:
    """Return a caller-safe copy of bundled fixture opportunities."""
    return deepcopy(FIXTURE_OPPORTUNITIES)
